# fly.toml app configuration file generated for guesslist on 2023-07-31T08:19:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "guesslist"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="guesslist_data"
  destination="/data"
